# Generated by Django 3.0.6 on 2020-06-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='이름')),
                ('phone', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='전화번호')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '예약자 명단',
                'verbose_name_plural': '예약자 명단',
                'db_table': '예약자 명단',
            },
        ),
        migrations.CreateModel(
            name='ReservState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserv', models.CharField(max_length=256, verbose_name='예약상태')),
            ],
            options={
                'verbose_name': '예약 상태',
                'verbose_name_plural': '예약상태',
                'db_table': '예약state',
            },
        ),
        migrations.CreateModel(
            name='ReservTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256, verbose_name='예약시간')),
            ],
            options={
                'verbose_name': '예약시간',
                'verbose_name_plural': '예약시간',
                'db_table': '예약시간',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=256, verbose_name='테이블번호')),
            ],
            options={
                'verbose_name': '테이블',
                'verbose_name_plural': '테이블',
                'db_table': '테이블',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.DateField(verbose_name='날짜')),
                ('party_num', models.IntegerField(verbose_name='예약자일행')),
                ('Reserv_day', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Customer', verbose_name='예약자')),
                ('reserv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.ReservState', verbose_name='상태')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Tables', verbose_name='테이블')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.ReservTime', verbose_name='예약시간')),
            ],
            options={
                'verbose_name': '예약 명단',
                'verbose_name_plural': '예약 명단',
                'db_table': '예약 명단',
            },
        ),
    ]
